
#' Conditional inferences
#'
#' Calculate estimands conditional on observed data (currently, for single-case process tracing) together with data realization probabilities
#' Realization probabilities are the probability of the observed data given data is sought on observed node
#' @param model A model generated by \code{make_model}.
#' @param parameters A numeric vector. Values of parameters may be specified. By default, it is drawn from priors.
#' @param query A character vector of length 1L. Query for example 'Y[X=1]>Y[X=0]'
#' @param given A conditioning set as a character string that evaluates to a logical, for example 'Y==1'
#'
#' @export
#' @examples
#' model <- make_model("X->Y")
#' model <- set_parameters(model, type = "flat")
#' conditional_inferences(model, query = "Y[X=1]>Y[X=0]")
#'
#' # Example of posteriors given monotonic X -> M -> Y model
#' model <- make_model("X-> M -> Y")  %>%
#'   set_restrictions(labels = list(M = "10", Y = "10"))
#' conditional_inferences(model, query = "Y[X=1]>Y[X=0]", given = "Y==1")
#'
#' # Running example
#' model <- make_model("S -> C -> Y <- R <- X; X -> C -> R") %>%
#'    set_restrictions(labels =
#'    list(C = "C1110", R = "R0001", Y = "Y0001"), keep = TRUE)
#' conditional_inferences(model, query = list(COE = "(Y[S=0] > Y[S=1])"),
#' given = "Y==1 & S==0")

conditional_inferences <- function(model, query, parameters=NULL,  given = NULL){

	if(is.null(parameters)) parameters <- get_parameters(model)

	vars <- model$node

	# Possible data
	vals <-  all_data_types(model, given = given) %>% select(-event)

	# Conditions
	conds <- t(apply(vals, 1, function(j) paste(vars, j, sep = "==")))
	conds[is.na(vals)] <- NA
	subsets <- apply(conds, 1, function(j) paste(j[!is.na(j)], collapse = " & "))
	subsets <- as.list(subsets)
	subsets[subsets==""] <- paste0(model$nodes[1], ">-1") # Guaranteed true

	impossible <- lapply(subsets, function(s) all(!(get_query_types(model, s)$types))) %>% unlist
	vals     <- vals[!impossible, ]
	subsets  <- subsets[!impossible]

	# Calculate estimands
	estimands <- query_model(
		model   = model,
		parameters  = parameters,
		using = "parameters",
		queries = query,
		subsets = subsets)$mean

	# Cac=lculate data probabilities
	probs <- unlist(get_data_probs(model, data = vals))

	out <- data.frame(cbind(vals, estimands, probs))

	names(out) <- c(vars, "posterior", "prob")

	data.frame(out)
}
